name: FTP Sync

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to FTP
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftpupload.net
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        local-dir: ./
        server-dir: /htdocs/
        exclude: |
          **/.git*
          **/.git*/**
          README.md
          .github/**
          config.php
          .env.exemple
